site_name: b4sh0xf offsec notes
site_description: writeups, study notes and tricks on offensive security
site_author: b4sh0xf
plugins:
  - search
  # - git-revision-date-localized:
  #    enable_creation_date: true
  #       type: timeago
  #       locale: en
  #       fallback_to_build_date: false
  #       enable_creation_date: true
  #       exclude:
  #           - index.md
  #       enabled: true
  #       strict: true
  # - glightbox
theme:
  name: material
  favicon: images/telefono.ico
  logo: images/tsushima.png
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - content.code.annotate
    - content.code.copy
    - navigation.top
    # - navigation.sections
    # - navigation.expand
    # - navigation.sections
  palette:
    # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Automatic light-dark mode toggling

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    code: Fira Code

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/b4sh0xf
    - icon: fontawesome/brands/twitter
      link: https://x.com/b4sh0xf
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@ghupasselongo
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/gustavo-linhares0xf
copyright: 🌐 all content is authoral. keep hacking ;)</a>

repo_url: https://github.com/b4sh0xf/b4sh0xf.github.io
repo_name: b4sh0xf/offsec
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - footnotes
  - def_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

docs_dir: docs/
nav:
  # This does not show up on the navbar. The Index word is specifically hidden in nav.html
  - home: index.md

  # about section
  - about me: about.md

  # programming
  - programming notes:
    - building an api in node: coding/nodeapi.md
    - basic webapp in php: coding/webapphp.md
    - building an api in golang: coding/apigo.md
    - websockets in golang: coding/wsgo.md
    - data structures in C:
      - stack: coding/stack.md
      - queue: coding/queue.md
      - linked list: coding/linkedlist.md
      - binary search tree: coding/bst.md
      - hash map: coding/hashmap.md
    - algorithms in C++: coding/algorithms.md
    - building a simple app in kotlin: coding/kotlin.md
    - building a simple app in flutter: coding/flutter.md
  # hacking
  - pentesting notes:
      - web exploitation:
        - xss: web/xss.md
        - sqli: web/sqli.md
        - ssti:
          - jinja2: web/ssti/jinja.md
          - spring: web/ssti/spring.md
          - erb: web/ssti/erb.md
          - pug.js: web/ssti/pug.md
          - ejs: web/ssti/ejs.md
          - twig: web/ssti/twig.md
        - lfi/rfi: web/lfi.md
        - insecure deserialization:
          - php: web/insecure/php.md
          - python: web/insecure/python.md
          - java: web/insecure/java.md
          - asp.net: web/insecure/dotnet.md
          - phar deserialization: web/insecure/phar.md
        - http request smuggling: web/desync.md
        - prototype pollution: web/pollution.md
        - type confusion: web/tconf.md
        - race condition: web/race.md
        - business logic: web/blogic.md
        - waf bypass: web/waf.md
        - web cache poisoning (PT-BR): web/wcp.md
        - off-by-slash: web/slash.md
        - zip-slip: web/zslip.md
      - api exploitation:
        - bola: web/api/bola.md
        - bopla: web/api/bopla.md
        - bfla: web/api/bfla.md
        - sspp: web/api/sspp.md
        - json injection: web/api/jsoni.md
        - improper inventory management: web/api/iim.md
        - ssrf: web/api/ssrf.md
        - jwt hacking: web/api/jwt.md
      - mobile exploitation:
        - android:
          - os fundamentals: mobile/os.md
          - apps fundamentals: mobile/apps.md
          - bypassing:
            - root detection: mobile/detections/root.md
            - frida detection: mobile/detections/frida.md
            - ssl pinning: mobile/detections/pinning.md
            - anti-emulator: mobile/detections/emulator.md
          - common vulnerabilities:
            - insecure data storage: mobile/ids.md
            - deeplinks: mobile/deeplinks.md
            - webviews: mobile/webviews.md
            - ipc: mobile/ipc.md
      - cloud exploitation:
        - about cloud computing: cloud/about.md
        - aws:
          - introduction: cloud/aws/intro.md
          - interacting with api-cli: cloud/aws/cli.md
          - lambda functions and api gw: cloud/aws/lambda.md
          - rds: cloud/aws/rds.md
          - ssrf2aws: cloud/aws/ssrf2aws.md
        - docker:
          - about docker: cloud/docker/about.md
          - interacting with docker cli and api: cloud/docker/cli.md
          - docker compose: cloud/docker/compose.md
        - kubernetes:
          - about kubernetes: cloud/k8s/about.md
      - active directory exploitation:
        - introduction to AD: ad/intro.md
        - kerberos: ad/kerberos.md
        - adcs: ad/adcs.md
        - ldap: ad/ldap.md
      - desktop applications:
        - exploiting electron apps: desktopapps/dvea/dvea.md

  - appsec notes:
    - ssdlc: appsec/ssdlc.md
    - threat modelling: appsec/tmodel.md
    - scans: appsec/scans.md

  # ctf writeups section
  - writeups:
      - hacking club:
        - writeup velorum: writeups/hc/velorum.md
        - writeup console: writeups/hc/console.md
        - writeups carnavown:
          - writeups/hc/imetrics.md
          - writeups/hc/iapi.md
      - hack the box:
        - celestial scribe: writeups/htb/cscribe.md
      - vulnlab:
        - writeup shibuya: writeups/vl/shibuya.md

  # tips and tricks section
  - tips and tricks:
    - bypassing client side encryption (PT-BR): ttricks/cse.md
    - privesc:
      - linux: ttricks/privesc/linux.md
      - windows: ttricks/privesc/windows.md
    - docker escape: ttricks/escape.md
    - kiosk escape: ttricks/kiosk.md
    - php sandbox escape: ttricks/phpscape.md
    - python sandbox escape: ttricks/pyscape.md
    - cheatsheets:
      - mobile cheatsheet: mobile/cheatsheet.md
      - ad cheatsheet: ttricks/adsheet.md
      - aws cheatsheet: ttricks/aws.md
    - pentesting wordpress: ttricks/pword.md
    - pentesting laravel: ttricks/plar.md
    - reverse engineering: lowlevel/reversing.md
    - format strings: lowlevel/fstrings.md
    - buffer overflow: lowlevel/bof.md
    - ret2libc: lowlevel/r2libc.md
    - rop: lowlevel/rop.md